@interface PSSpecifier : NSObject {
  SEL  _buttonAction;
  SEL  _confirmationAction;
  SEL  _confirmationCancelAction;
  SEL  _controllerLoadAction;
  NSString * _name;
  NSMutableDictionary * _properties;
  NSDictionary * _shortTitleDict;
  bool  _showContentString;
  NSDictionary * _titleDict;
  id  _userInfo;
  NSArray * _values;
  SEL  action;
  long long  autoCapsType;
  long long  autoCorrectionType;
  SEL  cancel;
  long long  cellType;
  Class  detailControllerClass;
  Class  editPaneClass;
  SEL  getter;
  long long  keyboardType;
  SEL  setter;
  id  target;
  unsigned long long  textFieldType;
}

@property (nonatomic) long long cellType;
@property (nonatomic, retain) Class detailControllerClass;
@property (nonatomic, retain) Class editPaneClass;
@property (nonatomic, retain) NSString *identifier;
@property (nonatomic, retain) NSString *name;
@property (nonatomic, retain) NSDictionary *shortTitleDictionary;
@property (nonatomic) bool showContentString;
@property (nonatomic, retain) id target;
@property (nonatomic, retain) NSDictionary *titleDictionary;
@property (nonatomic, retain) id userInfo;
@property (nonatomic, retain) NSArray *values;

// Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences

+ (long long)autoCapsTypeForString:(id)arg1;
+ (long long)autoCorrectionTypeForNumber:(id)arg1;
+ (id)deleteButtonSpecifierWithName:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)emptyGroupSpecifier;
+ (id)groupSpecifierWithID:(id)arg1;
+ (id)groupSpecifierWithID:(id)arg1 name:(id)arg2;
+ (id)groupSpecifierWithName:(id)arg1;
+ (long long)keyboardTypeForString:(id)arg1;
+ (id)preferenceSpecifierNamed:(id)arg1 target:(id)arg2 set:(SEL)arg3 get:(SEL)arg4 detail:(Class)arg5 cell:(long long)arg6 edit:(Class)arg7;
+ (id)specifierWithSpecifier:(id)arg1;

- (SEL)buttonAction;
- (long long)cellType;
- (SEL)confirmationAction;
- (SEL)confirmationCancelAction;
- (SEL)controllerLoadAction;
- (id)description;
- (Class)detailControllerClass;
- (Class)editPaneClass;
- (bool)hasValidGetter;
- (bool)hasValidSetter;
- (id)identifier;
- (id)init;
- (bool)isEqualToSpecifier:(id)arg1;
- (SEL)legacyAction;
- (SEL)legacyCancel;
- (void)loadValuesAndTitlesFromDataSource;
- (id)name;
- (id)objectForKeyedSubscript:(id)arg1;
- (void)performButtonAction;
- (void)performConfirmationAction;
- (void)performConfirmationCancelAction;
- (void)performControllerLoadAction;
- (id)performGetter;
- (void)performLegacyAction;
- (void)performSetterWithValue:(id)arg1;
- (id)properties;
- (id)propertyForKey:(id)arg1;
- (void)removePropertyForKey:(id)arg1;
- (void)setButtonAction:(SEL)arg1;
- (void)setCellType:(long long)arg1;
- (void)setConfirmationAction:(SEL)arg1;
- (void)setConfirmationCancelAction:(SEL)arg1;
- (void)setControllerLoadAction:(SEL)arg1;
- (void)setDetailControllerClass:(Class)arg1;
- (void)setEditPaneClass:(Class)arg1;
//- (void)setIdentifier:(id)arg1;
- (void)setKeyboardType:(long long)arg1 autoCaps:(long long)arg2 autoCorrection:(long long)arg3;
- (void)setLegacyAction:(SEL)arg1;
- (void)setLegacyCancel:(SEL)arg1;
//- (void)setName:(id)arg1;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)setProperties:(id)arg1;
- (void)setProperty:(id)arg1 forKey:(id)arg2;
//- (void)setShortTitleDictionary:(id)arg1;
- (void)setShowContentString:(bool)arg1;
- (void)setTarget:(id)arg1;
//- (void)setTitleDictionary:(id)arg1;
- (void)setUserInfo:(id)arg1;
//- (void)setValues:(id)arg1;
- (void)setValues:(id)arg1 titles:(id)arg2;
- (void)setValues:(id)arg1 titles:(id)arg2 shortTitles:(id)arg3;
- (void)setValues:(id)arg1 titles:(id)arg2 shortTitles:(id)arg3 usingLocalizedTitleSorting:(bool)arg4;
- (void)setVersionLabelEnabled:(bool)arg1;
- (void)setupIconImageWithBundle:(id)arg1;
- (void)setupIconImageWithPath:(id)arg1;
- (id)shortTitleDictionary;
- (bool)showContentString;
- (id)target;
- (long long)titleCompare:(id)arg1;
- (id)titleDictionary;
- (id)userInfo;
- (id)values;
- (bool)versionLabelEnabled;
@end
